import { StyleSheet } from 'react-native';

const Style = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EAF0F6',
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 28,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    title: {
        fontSize: 32,
        fontWeight: '700',
        color: '#333',
        marginBottom: 8,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: 24,
        textAlign: 'center',
    },
    input: {
        height: 50,
        borderRadius: 12,
        borderColor: '#ddd',
        borderWidth: 1,
        marginBottom: 16,
        paddingHorizontal: 16,
        backgroundColor: '#F9F9F9',
    },
    button: {
        backgroundColor: '#4a90e2',
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 8,
        shadowColor: '#4a90e2',
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 6,
        elevation: 3,
    },
    buttonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    signUpContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 16,
    },
    signUpText: {
        color: '#666',
        fontSize: 15,
    },
    signUpLink: {
        color: '#4a90e2',
        fontSize: 15,
        fontWeight: '600',
    },
        passwordToggle: {
        position: 'absolute',
        right: 16,
        top: 14,
    },
    inputWrapper: {
        position: 'relative',
        marginBottom: 16,
    },
    errorText: {
        color: 'red',
        fontSize: 13,
        marginTop: -10,
        marginBottom: 10,
        paddingHorizontal: 4,
    },
    disabledButton: {
        backgroundColor: '#a0c5ed',
    },
        networkBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    networkModal: {
        width: '85%',
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
    },
    networkTitle: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 10,
        color: '#333',
        textAlign: 'center',
    },
    networkMessage: {
        fontSize: 15,
        textAlign: 'center',
        marginBottom: 20,
        color: '#666',
    },
    networkRetryButton: {
        backgroundColor: '#4a90e2',
        paddingVertical: 10,
        paddingHorizontal: 25,
        borderRadius: 8,
    },
    networkRetryText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 15,
    },
     overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1000,
        flexDirection: 'row',
    },
    overlayBackground: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    sidebar: {
        width: 300,
        backgroundColor: '#f8f9fa',
        borderRightWidth: 1,
        borderColor: '#e9ecef',
        flexDirection: 'column',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    sidebarHeader: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e9ecef',
        backgroundColor: '#fff',
    },
    sidebarTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#212529',
        marginBottom: 12,
    },
    closeButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#e9ecef',
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeButtonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#495057',
    },
    newChatButton: {
        backgroundColor: '#007bff',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
        alignItems: 'center',
    },
    newChatButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    chatList: {
        flex: 1,
        padding: 8,
    },
    chatItem: {
        padding: 12,
        marginVertical: 4,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    chatItemActive: {
        backgroundColor: '#007bff',
        borderColor: '#007bff',
    },
    chatItemTitle: {
        fontSize: 14,
        fontWeight: '500',
        color: '#212529',
        marginBottom: 4,
    },
    chatItemTitleActive: {
        color: '#fff',
    },
    chatItemTime: {
        fontSize: 12,
        color: '#6c757d',
        marginBottom: 2,
    },
    chatItemTimeActive: {
        color: '#e3f2fd',
    },
    chatItemPreview: {
        fontSize: 12,
        color: '#868e96',
    },
    chatItemPreviewActive: {
        color: '#e3f2fd',
    },
    headerContainer: {
        paddingTop: 40,
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e9ecef',
        backgroundColor: '#fff',
        flexDirection: 'row',
        alignItems: 'center',
    },
    menuButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f8f9fa',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    menuButtonText: {
        fontSize: 18,
        color: '#495057',
    },
    headerTextContainer: {
        flex: 1,
        alignItems: 'center',
    },
    headerSpacer: {
        width: 52,
    },
    header: {
        fontSize: 24,
        fontWeight: '700',
        color: '#212529',
        textAlign: 'center',
    },
    chatSubtitle: {
        fontSize: 14,
        color: '#6c757d',
        textAlign: 'center',
        marginTop: 4,
    },
    chatContent: {
        flexGrow: 1,
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyStateText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#495057',
        marginBottom: 8,
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: '#6c757d',
        textAlign: 'center',
        marginBottom: 16,
    },
    messageCounter: {
        fontSize: 12,
        color: '#6c757d',
        textAlign: 'center',
        fontStyle: 'italic',
    },
    messageCounterContainer: {
        alignItems: 'center',
        marginTop: 8,
    },
    messageBubble: {
        marginVertical: 6,
        padding: 12,
        borderRadius: 12,
        maxWidth: '80%',
        alignSelf: 'flex-start',
    },
    userBubble: {
        alignSelf: 'flex-end',
        backgroundColor: '#007bff',
    },
    aiBubble: {
        backgroundColor: '#f8f9fa',
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    messageText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#212529',
    },
    userMessageText: {
        color: '#fff',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
    },
    loadingText: {
        marginLeft: 8,
        fontSize: 14,
        color: '#6c757d',
    },
    inputContainer: {
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#e9ecef',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 8,
        paddingTop: 10,
    },
    chatInput: {
        flex: 1,
        borderColor: '#ced4da',
        borderWidth: 1,
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 10,
        fontSize: 14,
        maxHeight: 100,
        backgroundColor: '#fff',
    },
    sendButton: {
        backgroundColor: '#007bff',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
    },
    sendButtonDisabled: {
        backgroundColor: '#6c757d',
    },
    sendButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
});

export default Style;
